# Generated by Django 6.0.1 on 2026-02-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dailyreflection'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='daily_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='last_completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='weekly_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='DailyReflection',
        ),
    ]
