# Generated by Django 6.0.1 on 2026-02-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_dailyreflection_options_alter_habit_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymactivity',
            name='intensity',
            field=models.CharField(max_length=10),
        ),
    ]
