# Generated by Django 6.0.1 on 2026-02-03 12:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_gymactivity_intensity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='stepslog',
            old_name='achieved_steps',
            new_name='steps',
        ),
        migrations.RenameField(
            model_name='stepslog',
            old_name='target_steps',
            new_name='target',
        ),
        migrations.RemoveField(
            model_name='stepslog',
            name='achieved',
        ),
        migrations.RemoveField(
            model_name='stepslog',
            name='source',
        ),
        migrations.AlterField(
            model_name='stepslog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='GymLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_part', models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('arms', 'Arms'), ('legs', 'Legs'), ('core', 'Core'), ('calves', 'Calves')], max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'body_part', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='GymActivity',
        ),
    ]
