# Generated by Django 6.0.1 on 2026-02-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_playerprofile_protein_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlog',
            name='food_xp_awarded',
            field=models.BooleanField(default=False),
        ),
    ]
